; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "He thong Quan ly Dao tao Sau dai hoc"
#define MyAppVersion "1.0"
#define MyAppPublisher "Nhom 13 - HUIT"
#define MyAppExeName "QldtSdh.Wpf.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
AppId={{7F6A2C29-847C-4C69-959D-3522E9B4895C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\QldtSdh
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir=C:\Users\DANGQUANGHOA\Desktop\Do-An-Dotnet\frontend
OutputBaseFilename=QldtSdh_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SetupIconFile=C:\Users\DANGQUANGHOA\Desktop\Do-An-Dotnet\frontend\QldtSdh.Wpf\hinh-dai-dien.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\DANGQUANGHOA\Desktop\Do-An-Dotnet\frontend\QldtSdh.Wpf\bin\Release\net10.0-windows\win-x64\publish\QldtSdh.Wpf.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\DANGQUANGHOA\Desktop\Do-An-Dotnet\frontend\QldtSdh.Wpf\bin\Release\net10.0-windows\win-x64\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
